Merge projects

diff --git a/scripts/readlist b/scripts/readlist
--- a/scripts/readlist
+++ b/scripts/readlist
@@ -6,4 +6,9 @@ if [ -z "$1" ]
     exit 1
 fi
 
+if [ ! -f $1 ]; then
+    echo "File not found!"
+    exit 2
+fi
+
 awk '!/^ *#/ && NF' "$1"
